### ISSUE TITLE
'Polygon'의 번역

### ISSUE THREAD

**Issue by HuidaeCho** [HuidaeCho/grass-ko#11]
'Polygon'을 '다각형'으로 번역해 오고 있었는데 '다각형'과 '폴리곤' 둘 중 어느 쪽이 더 적당한지요? 국내 GIS 사용자들 사이에서 더 많이 통용되는 용어로 번역하는 것이 좋아 보입니다. 만약 폴리곤으로 결정한다면 다각형으로 번역된 기존의 문자열을 모두 바꿀 필요가 있어 보입니다. 어떻게 생각하시는지 의견 부탁드립니다.

제가 처음 '다각형'으로 번역한 이유는 'Point'를 '포인트'라고 번역하기 보다 '점'으로 번역하는 것이 더 자연스럽다는 판단하에 일관적으로 Point (점), Line (선), Polygon (다각형)으로 번역했습니다.

이 부분에 있어서는 개인적으로 아직 판단을 유보한 상태입니다.

**Comment by yungjinsung** [comment]
어려운 화두입니다. 저도 보고서나 제안서 등에서 혼용할 때가 많습니다. 
꼭 필요한 경우를 제외하고는 "다각형", "선", "점"으로 쓰겠습니다. 

아래와 같은 Geometry Type 을 비교할 때 외에는 한글을 쓰도록 하겠습니다. 
- Point, Line(Polyline), Polygon
- Multi-Point, Multi-Polyline, Multi-Polygon
- PointM, PolylineM, PolygonM
- PointZ, PolylineZ, PolygonZ

그런데, GRASS에서도 위의 타입을 지원하나요?

**Comment by HuidaeCho** [comment]
GRASS는 토폴로지 중심으로 자료형이 구성되어 있고 2차원 3차원 자료형의 구분이 없습니다.
* point
* line
* area
* centroid
* boundary (면들이 공유하는 선)
* island (다각형 안에 구멍)
으로 구성되어 있습니다. 3차원 속성이 Z에 해당되지만 따로 자료형이 있는 것은 아닙니다. 그리고 M은 없습니다. Multi-*도 없습니다. 그래서 Multipoints는 걱정할 필요가 없어 보입니다.

**Comment by HuidaeCho** [comment]
* point: 점
* line; 선
* polygon: 다각형
* geometry: 도형
으로 결론났습니다.
