### ISSUE TITLE
'Snap'의 번역

### ISSUE THREAD

**Issue by HuidaeCho** [HuidaeCho/grass-ko#12]
'Snapping'을 '스냅'으로 번역하셨습니다. 발음을 그대로 적는 것이 더 이해하기 쉬울까요? 용어집에는 '끌어 붙이기'라고 되어 있습니다.

**Comment by HuidaeCho** [comment]
* 끌어 붙이기 vs. 스냅핑
* 끌어 붙이다 vs. 스냅하다

일단 용어집에는 '스냅핑', '스냅하다'로 등제했습니다만... 뭔가 '끌어 붙이기'나 '스냅핑' 둘 다 썩 마음에 들지 않습니다. ㅋㅋ 이런식으로 동사조차 발음을 한글로 적는 경우 때문에 번역의 범위를 정하는 것이 쉽지 않습니다.

**Comment by yungjinsung** [comment]
기존의 GIS 나 CAD 툴을 다루시는 분들은 스냅핑이 더 자연스러울 것 같습니다. 처음 접하시는 분들은 오히려 "끌어 붙이기", "끌어 붙이다"가 이해가 빠를 것 같습니다.

**Comment by HuidaeCho** [comment]
'끌어 붙이기(snapping)', '끌어 붙이다(snap)'으로 하기엔 너무 길 수도 있어서... 저는 솔직히 모르겠습니다. 그런데 한편으로 생각하면 GRASS로 snap을 처음 접하는 GIS 유저라면 GRASS의 사용 '불'편이성을 생각하면 좋은 GIS 선택은 아닐 거라 생각합니다. 그래서.. 일단 '스냅'으로 진행했다가 이변이 생겨서 사용자가 많아지면 다시 생각해 보는 것도 방법 같습니다.

**Comment by HuidaeCho** [comment]
QGIS는 어떻게 번역되어 있는지요?

**Comment by HuidaeCho** [comment]
QGIS가 snap의 번역이 있으면 그를 따르고 없으면 '스냅'으로 발음을 일단 적기로 하겠습니다.

**Comment by HuidaeCho** [comment]
앗 다시 끌어붙이기로 바꾸셨네요? 그럼 '끌어 붙이기'로 하지요.

이렇게 하는게 좋을 것 같습니다. 일단 Glossary를 켜시고 Glossary에 따라 번역(띄어쓰기 포함)을 하시다가 영 아니다 싶으신 부분은 여기서 같이 얘기를 나누는게 오락가락하지 않고 좋을 것 같습니다. 이곳에 올린 CSV 파일을 보셔도 좋습니다.

**Comment by HuidaeCho** [comment]
Glossary 다시 업데이트했습니다

**Comment by HuidaeCho** [comment]
CSV 파일을 수정하시고 PR를 주셔도 좋습니다. 그러면 제가 Glossary를 수정할 수 있습니다. Glossary 수정 권한이 있으실 겁니다.

**Comment by HuidaeCho** [comment]
Snap은 그럼 '끌어 붙이다'로 하겠습니다. 누군가 나타나서 이게 뭔소리야 할 때까지 말이죠. ㅎㅎ
