### ISSUE TITLE
Model: 모델, 모형

### ISSUE THREAD

**Issue by HuidaeCho** [HuidaeCho/grass-ko#17]
기존 '모형'과 새로운 '모델'이 있습니다.

그런데 기존의 '모델링 언어'와 '모델러'도 있습니다. ㅜㅠ

**Comment by yungjinsung** [comment]
"모델"이라는 용어 자체를 그대로 쓰는 경우가 많아, "모형"일 때 오히려 어색할 수 있지 않을까요?
"모델링 언어"와 "모델러"는 아래와 같이 구분하는게 어떨까요?
- 모델링 언어: 모델을 구성하기 위한 스크립트 또는 개발 언어
- 모델러 : 모델을 구성하기 위한 GUI 또는 Tool

**Comment by HuidaeCho** [comment]
동의합니다. "모델"로 통일하겠습니다. 특정분야에서 통용되는 모형이 (예를 들어 수문모형) 아니면 모두 모델로 하는 것이 좋겠습니다.
