### ISSUE TITLE
Label: 레이블, 꼬리표

### ISSUE THREAD

**Issue by HuidaeCho** [HuidaeCho/grass-ko#19]
지금까지 '꼬리표'라고 번역하고 있었는데 오늘 보니 좀 그렇습니다.
* label (n): 레이블, 꼬리표
* label (v): 레이블하다? 레이블 달다? 꼬리표를 달다

동사로 바꾸려니 애매해지는 면이 생깁니다. 아마도 '레이블', '레이블 달다'가 '꼬리표'보다 나을까요? QGIS에 대응하는 한글 단어가 있는지요?

**Comment by yungjinsung** [comment]
QGIS에서는 "라벨"을 사용하고 있습니다. 
동사인 경우에는 라벨을 추가/수정/변경 등으로 뒤에 동사를 붙여 사용하는 건 어떨까요?

**Comment by HuidaeCho** [comment]
일단, QGIS는 영어 발음을 쓰고 있군요. 그런데 "라벨"은 너무 아재식 발음 같습니다. 영어 발음을 그대로 쓰는데 영미권에서는 통하지 않는 발음입니다. QGIS가 왜 "라벨"로 번역했는지 이해가 안 되는 부분입니다. [국립국어원의 외래어 표기법 용례 찾기](http://kornorms.korean.go.kr/example/exampleList.do?regltn_code=0003)를 봐도 "라벨"은 지명에만 해당되고 일반 용어는 "레이블", "레이블링"으로 표기하고 있습니다. "레이블"로 통일하는 것이 좋겠습니다.
