### ISSUE TITLE
'Null'의 번역

### ISSUE THREAD

**Issue by HuidaeCho** [HuidaeCho/grass-ko#2]
'Null'은 Glossary에 따르면 '널'로 번역을 해오고 있었습니다.

**Comment by yungjinsung** [comment]
저도 "널"로 하도록 하겠습니다. "값 없음"을 생각해 봤는데, 아무래도 "Empty"와는 헷갈릴 것 같습니다.

**Comment by HuidaeCho** [comment]
Null은 널로 번역하기로 했습니다.
