### ISSUE TITLE
'Name'의 번역

### ISSUE THREAD

**Issue by HuidaeCho** [HuidaeCho/grass-ko#3]
'Name'을 '이름'으로 번역하다가 'DB Name'을 'DB 이름'으로 번역하니 이상하군요. 일관성 없지만 그냥 'Name'은 '이름'으로 '... Name'은 '...명'으로 하는 것이 더 좋을까요?

**Comment by yungjinsung** [comment]
네, 자연스러운 것 같습니다. "Name"을 "명칭"으로 생각도 해 봤는데, 사실 "이름"이 한글이고 더 좋은 것 같습니다.

**Comment by HuidaeCho** [comment]
그럼 모두 '이름'으로 번역하도록 하지요. DB 이름, 래스터 지도의 이름. 규칙을 단순화하는게 좋을 것 같습니다. 생각이 너무 많으면 진행이 더뎌지니까요.
