### ISSUE TITLE
'RAM'의 번역

### ISSUE THREAD

**Issue by HuidaeCho** [HuidaeCho/grass-ko#6]
'RAM'을 'RAM'으로 쓰셨습니다. '램'과 'RAM' 이건 저도 잘 모르겠습니다.

**Comment by yungjinsung** [comment]
앞으로는 "램"으로 쓰겠습니다. 발음 그대로 써도 명확한 전달이 되니 가능하면 한글로 쓰겠습니다.

**Comment by HuidaeCho** [comment]
* DB: DB
* RAM: RAM? 램?

'디비'는 '램'에 비해 너무 아닌 것 같지만 '램'은 많이들 한글로 쓰는 것 같습니다. 이걸 일단 '램'으로 쓰기로 했습니다.

**Comment by HuidaeCho** [comment]
Glossary 업데이트했습니다.
