### ISSUE TITLE
'Feature'의 번역

### ISSUE THREAD

**Issue by HuidaeCho** [HuidaeCho/grass-ko#8]
'Feature'를 '피쳐'로 번역하고 있었는데 '피처'로 쓰쎴습니다. 외래어 표기법에 따라 '피처'로 통일하는 것이 맞는 것 같습니다. https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=100744

**Comment by yungjinsung** [comment]
GIS에서는 "객체", "개체" 로 표현하는 경우도 있는데, "Object"와도 혼동을 줄 것같으니, "피처"로 쓰게습니다.

**Comment by HuidaeCho** [comment]
동의합니다.
