### ISSUE TITLE
'Category'의 번역

### ISSUE THREAD

**Issue by HuidaeCho** [HuidaeCho/grass-ko#9]
'Category'를 발음대로 '카테고리'로 하는 것이 '범주'보다 나을까요? 지금까지 '범주'로 번역하고 있었습니다.

**Comment by yungjinsung** [comment]
"구분", "범주", "분류" 등로 할 수 있는데요. "범주"로 번역하게습니다.

**Comment by HuidaeCho** [comment]
* category: 범주
로 결론났습니다.
